from __future__ import annotations

import json
from pathlib import Path

from sqlmodel import select

from backend.app.agents.codex_exec import ExecCommandResult
from backend.app.agents.codex_run import CodexRunService
from backend.app.agents.run_folder import RunFolderSpec, RunInputFile
from backend.app.db.models import AuditLog, ImportedFile, MasterCvProfileSnapshot, PolicySnapshot, Run, UserProfileSnapshot, ValidationResult


def _valid_user_profile() -> dict[str, object]:
    provenance = {
        "source_type": "user_claim",
        "confidence": 0.9,
        "needs_review": False,
        "source_refs": ["input/onboarding_notes.md"],
    }
    return {
        "schema_version": "1.0",
        "profile_id": "profile-codex-run",
        "created_at": "2026-05-15T00:00:00+00:00",
        "identity": {"display_name": "Generated User"},
        "preferences": {
            "target_roles": [{"value": "Backend engineer", "provenance": provenance}],
            "target_locations": [{"value": "Berlin", "provenance": provenance}],
            "remote_preferences": ["remote"],
            "communication_tone": {"value": "concise", "provenance": provenance},
        },
        "provenance_summary": {
            "source_documents": ["input/onboarding_notes.md"],
            "interview_notes": ["Generated by fake Codex runner."],
        },
    }


def _valid_master_cv_profile() -> dict[str, object]:
    provenance = {
        "source_type": "user_claim",
        "confidence": 0.9,
        "needs_review": False,
        "source_refs": ["input/onboarding_notes.md"],
    }
    return {
        "schema_version": "1.0",
        "profile_id": "profile-codex-run",
        "created_at": "2026-05-15T00:00:00+00:00",
        "claims": [
            {
                "claim_id": "claim-codex-run-backend",
                "category": "skill",
                "statement": "Generated User wants backend work in Berlin.",
                "provenance": provenance,
                "approved_for_tailoring": False,
            }
        ],
    }


def _valid_policy() -> dict[str, object]:
    return {
        "schema_version": "1.0",
        "policy_id": "policy-codex-run",
        "created_at": "2026-05-15T00:00:00+00:00",
        "exclusions": {"industries": [], "company_names": [], "domains": [], "keywords": []},
        "outreach": {
            "allow_company_repeat": False,
            "allow_recipient_repeat": False,
            "company_dedupe_window_days": 365,
            "recipient_dedupe_window_days": 365,
            "require_manual_review_before_send": True,
        },
        "limits": {"daily_send_limit": 0, "weekly_send_limit": 0},
        "review_thresholds": {"minimum_required_confidence": 0.8, "block_needs_review_required_fields": True},
    }


def _valid_onboarding_review(run_id: str) -> dict[str, object]:
    return {
        "schema_version": "1.0",
        "review_id": f"review-{run_id}",
        "run_id": run_id,
        "created_at": "2026-05-15T00:00:00+00:00",
        "items": [],
    }


class WritingRunner:
    def __init__(self, payload: dict[str, object]) -> None:
        self.payload = payload
        self.calls: list[tuple[list[str], Path]] = []

    def __call__(self, args, cwd, timeout, env):
        self.calls.append((list(args), cwd))
        output_dir = cwd / "output"
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "user_profile.json").write_text(json.dumps(self.payload), encoding="utf-8")
        (output_dir / "master_cv_profile.json").write_text(json.dumps(_valid_master_cv_profile()), encoding="utf-8")
        (output_dir / "policy.json").write_text(json.dumps(_valid_policy()), encoding="utf-8")
        (output_dir / "onboarding_review.json").write_text(json.dumps(_valid_onboarding_review(cwd.name)), encoding="utf-8")
        return ExecCommandResult(returncode=0, stdout='{"event":"completed"}\n', stderr="")


class FailingRunner:
    def __call__(self, args, cwd, timeout, env):
        return ExecCommandResult(returncode=2, stdout='{"unsafe":"stdout is ignored"}', stderr="failed")


def test_codex_run_service_prepares_executes_imports_and_exposes_dashboard_state(client, db_session, runs_root):
    runner = WritingRunner(_valid_user_profile())

    result = CodexRunService(session=db_session, runner=runner).prepare_execute_import(
        RunFolderSpec(
            run_id="codex-run-success",
            task="Generate user_profile.json from scoped onboarding notes.",
            inputs=(RunInputFile("onboarding_notes.md", "Generated User wants backend work in Berlin."),),
            expected_output_files=("user_profile.json", "master_cv_profile.json", "policy.json", "onboarding_review.json"),
            metadata={"task_type": "onboarding_profile"},
        ),
        run_type="onboarding_chat",
    )

    assert result.execution.status == "succeeded"
    assert result.import_result is not None
    assert result.import_result.run.status == "imported"
    assert runner.calls[0][1] == runs_root / "codex-run-success"
    assert (runs_root / "codex-run-success" / "manifest.json").exists()
    assert (runs_root / "codex-run-success" / "logs" / "codex_exec.json").exists()

    snapshot = db_session.exec(select(UserProfileSnapshot)).one()
    assert snapshot.profile_id == "profile-codex-run"
    assert snapshot.status == "candidate"
    assert db_session.exec(select(MasterCvProfileSnapshot)).one().status == "candidate"
    assert db_session.exec(select(PolicySnapshot)).one().status == "candidate"
    assert len(db_session.exec(select(ImportedFile)).all()) == 4
    assert len(db_session.exec(select(ValidationResult)).all()) == 4

    run_response = client.get("/runs/codex-run-success")
    assert run_response.status_code == 200
    assert run_response.json()["status"] == "imported"
    validation_response = client.get("/runs/codex-run-success/validation-results")
    assert validation_response.status_code == 200
    assert validation_response.json()[0]["status"] == "schema_validation_passed"
    audit_response = client.get("/audit-logs", params={"run_id": "codex-run-success"})
    assert audit_response.status_code == 200
    actions = {entry["action"] for entry in audit_response.json()}
    assert {"run_folder_prepared", "codex_exec_completed", "import_completed"}.issubset(actions)


def test_codex_run_service_skips_import_when_execution_fails(db_session, runs_root):
    result = CodexRunService(session=db_session, runner=FailingRunner()).prepare_execute_import(
        RunFolderSpec(
            run_id="codex-run-failed",
            task="Generate user_profile.json from scoped onboarding notes.",
            inputs=(RunInputFile("onboarding_notes.md", "No output should be trusted from stdout."),),
            expected_output_files=("user_profile.json",),
        ),
        run_type="onboarding_chat",
    )

    assert result.execution.status == "failed"
    assert result.import_result is None
    run = db_session.exec(select(Run).where(Run.run_id == "codex-run-failed")).one()
    assert run.status == "codex_exec_failed"
    assert db_session.exec(select(ImportedFile)).all() == []
    assert db_session.exec(select(ValidationResult)).all() == []

    skipped = db_session.exec(select(AuditLog).where(AuditLog.action == "codex_run_import_skipped")).one()
    assert skipped.result_status == "skipped"
    assert json.loads(skipped.reason_codes_json) == ["nonzero_exit"]
    assert (runs_root / "codex-run-failed" / "logs" / "codex_exec.json").exists()
