"""create phase 2 domain tables

Revision ID: 0176dbbb5e28
Revises: 20260513_0001
Create Date: 2026-05-13 20:16:22.554773
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel



revision: str = '0176dbbb5e28'
down_revision: str | None = '20260513_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('normalized_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_policy_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_policy_key_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry_tags_json', sa.Text(), nullable=True),
    sa.Column('locations_json', sa.Text(), nullable=True),
    sa.Column('remote_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_refs_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_flags_json', sa.Text(), nullable=True),
    sa.Column('policy_conflicts_json', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=True)
    op.create_index(op.f('ix_companies_company_policy_key'), 'companies', ['company_policy_key'], unique=False)
    op.create_index(op.f('ix_companies_company_policy_key_kind'), 'companies', ['company_policy_key_kind'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_normalized_domain'), 'companies', ['normalized_domain'], unique=False)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.create_table('master_cv_profile_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_created_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_cv_profile_snapshots_content_hash'), 'master_cv_profile_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_master_cv_profile_snapshots_profile_id'), 'master_cv_profile_snapshots', ['profile_id'], unique=True)
    op.create_index(op.f('ix_master_cv_profile_snapshots_status'), 'master_cv_profile_snapshots', ['status'], unique=False)
    op.create_table('policy_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_created_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_snapshots_content_hash'), 'policy_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_policy_snapshots_policy_id'), 'policy_snapshots', ['policy_id'], unique=True)
    op.create_index(op.f('ix_policy_snapshots_status'), 'policy_snapshots', ['status'], unique=False)
    op.create_table('user_profile_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_created_at', sa.DateTime(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_snapshots_content_hash'), 'user_profile_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_user_profile_snapshots_profile_id'), 'user_profile_snapshots', ['profile_id'], unique=True)
    op.create_index(op.f('ix_user_profile_snapshots_status'), 'user_profile_snapshots', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('external_company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_recipient_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_refs_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_flags_json', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_contact_id'), 'contacts', ['contact_id'], unique=True)
    op.create_index(op.f('ix_contacts_email_source'), 'contacts', ['email_source'], unique=False)
    op.create_index(op.f('ix_contacts_external_company_id'), 'contacts', ['external_company_id'], unique=False)
    op.create_index(op.f('ix_contacts_normalized_recipient_email'), 'contacts', ['normalized_recipient_email'], unique=False)
    op.create_table('fit_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('external_company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_profile_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('policy_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('risks_json', sa.Text(), nullable=True),
    sa.Column('source_refs_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_flags_json', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.ForeignKeyConstraint(['policy_snapshot_id'], ['policy_snapshots.id'], ),
    sa.ForeignKeyConstraint(['user_profile_snapshot_id'], ['user_profile_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fit_evaluations_company_id'), 'fit_evaluations', ['company_id'], unique=False)
    op.create_index(op.f('ix_fit_evaluations_decision'), 'fit_evaluations', ['decision'], unique=False)
    op.create_index(op.f('ix_fit_evaluations_evaluation_id'), 'fit_evaluations', ['evaluation_id'], unique=True)
    op.create_index(op.f('ix_fit_evaluations_external_company_id'), 'fit_evaluations', ['external_company_id'], unique=False)
    op.create_index(op.f('ix_fit_evaluations_policy_snapshot_id'), 'fit_evaluations', ['policy_snapshot_id'], unique=False)
    op.create_index(op.f('ix_fit_evaluations_user_profile_snapshot_id'), 'fit_evaluations', ['user_profile_snapshot_id'], unique=False)
    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('external_company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('external_contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('claim_refs_json', sa.Text(), nullable=True),
    sa.Column('source_refs_json', sa.Text(), nullable=True),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_flags_json', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_company_id'), 'email_drafts', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_contact_id'), 'email_drafts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_draft_id'), 'email_drafts', ['draft_id'], unique=True)
    op.create_index(op.f('ix_email_drafts_external_company_id'), 'email_drafts', ['external_company_id'], unique=False)
    op.create_index(op.f('ix_email_drafts_external_contact_id'), 'email_drafts', ['external_contact_id'], unique=False)
    op.create_table('send_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('external_company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('external_contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_draft_id', sa.Integer(), nullable=True),
    sa.Column('external_email_draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_recipient_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_recipient_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('source_refs_json', sa.Text(), nullable=True),
    sa.Column('claim_refs_json', sa.Text(), nullable=True),
    sa.Column('policy_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('external_policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_profile_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('external_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('master_cv_profile_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('external_master_cv_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_flags_json', sa.Text(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], ),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.ForeignKeyConstraint(['master_cv_profile_snapshot_id'], ['master_cv_profile_snapshots.id'], ),
    sa.ForeignKeyConstraint(['policy_snapshot_id'], ['policy_snapshots.id'], ),
    sa.ForeignKeyConstraint(['user_profile_snapshot_id'], ['user_profile_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_intents_company_id'), 'send_intents', ['company_id'], unique=False)
    op.create_index(op.f('ix_send_intents_contact_id'), 'send_intents', ['contact_id'], unique=False)
    op.create_index(op.f('ix_send_intents_email_draft_id'), 'send_intents', ['email_draft_id'], unique=False)
    op.create_index(op.f('ix_send_intents_external_company_id'), 'send_intents', ['external_company_id'], unique=False)
    op.create_index(op.f('ix_send_intents_external_contact_id'), 'send_intents', ['external_contact_id'], unique=False)
    op.create_index(op.f('ix_send_intents_external_email_draft_id'), 'send_intents', ['external_email_draft_id'], unique=False)
    op.create_index(op.f('ix_send_intents_external_master_cv_profile_id'), 'send_intents', ['external_master_cv_profile_id'], unique=False)
    op.create_index(op.f('ix_send_intents_external_policy_id'), 'send_intents', ['external_policy_id'], unique=False)
    op.create_index(op.f('ix_send_intents_external_profile_id'), 'send_intents', ['external_profile_id'], unique=False)
    op.create_index(op.f('ix_send_intents_intent_id'), 'send_intents', ['intent_id'], unique=True)
    op.create_index(op.f('ix_send_intents_master_cv_profile_snapshot_id'), 'send_intents', ['master_cv_profile_snapshot_id'], unique=False)
    op.create_index(op.f('ix_send_intents_normalized_recipient_email'), 'send_intents', ['normalized_recipient_email'], unique=False)
    op.create_index(op.f('ix_send_intents_policy_snapshot_id'), 'send_intents', ['policy_snapshot_id'], unique=False)
    op.create_index(op.f('ix_send_intents_run_id'), 'send_intents', ['run_id'], unique=False)
    op.create_index(op.f('ix_send_intents_status'), 'send_intents', ['status'], unique=False)
    op.create_index(op.f('ix_send_intents_user_profile_snapshot_id'), 'send_intents', ['user_profile_snapshot_id'], unique=False)
    op.create_table('imported_gate_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_result_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('send_intent_id', sa.Integer(), nullable=True),
    sa.Column('external_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checks_json', sa.Text(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('external_reservation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('policy_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('external_policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('imported_file_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_file_id'], ['imported_files.id'], ),
    sa.ForeignKeyConstraint(['policy_snapshot_id'], ['policy_snapshots.id'], ),
    sa.ForeignKeyConstraint(['send_intent_id'], ['send_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_gate_results_external_intent_id'), 'imported_gate_results', ['external_intent_id'], unique=False)
    op.create_index(op.f('ix_imported_gate_results_external_policy_id'), 'imported_gate_results', ['external_policy_id'], unique=False)
    op.create_index(op.f('ix_imported_gate_results_external_reservation_id'), 'imported_gate_results', ['external_reservation_id'], unique=False)
    op.create_index(op.f('ix_imported_gate_results_gate_result_id'), 'imported_gate_results', ['gate_result_id'], unique=True)
    op.create_index(op.f('ix_imported_gate_results_policy_snapshot_id'), 'imported_gate_results', ['policy_snapshot_id'], unique=False)
    op.create_index(op.f('ix_imported_gate_results_send_intent_id'), 'imported_gate_results', ['send_intent_id'], unique=False)
    op.create_index(op.f('ix_imported_gate_results_status'), 'imported_gate_results', ['status'], unique=False)
    op.create_table('outreach_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('send_intent_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('normalized_recipient_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_policy_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['policy_snapshot_id'], ['policy_snapshots.id'], ),
    sa.ForeignKeyConstraint(['send_intent_id'], ['send_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_records_channel'), 'outreach_records', ['channel'], unique=False)
    op.create_index(op.f('ix_outreach_records_company_id'), 'outreach_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_company_policy_key'), 'outreach_records', ['company_policy_key'], unique=False)
    op.create_index(op.f('ix_outreach_records_contact_id'), 'outreach_records', ['contact_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_normalized_recipient_email'), 'outreach_records', ['normalized_recipient_email'], unique=False)
    op.create_index(op.f('ix_outreach_records_outreach_record_id'), 'outreach_records', ['outreach_record_id'], unique=True)
    op.create_index(op.f('ix_outreach_records_policy_snapshot_id'), 'outreach_records', ['policy_snapshot_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_send_intent_id'), 'outreach_records', ['send_intent_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_source'), 'outreach_records', ['source'], unique=False)
    op.create_index(op.f('ix_outreach_records_status'), 'outreach_records', ['status'], unique=False)
    op.create_table('send_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('send_intent_id', sa.Integer(), nullable=True),
    sa.Column('normalized_recipient_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_policy_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['policy_snapshot_id'], ['policy_snapshots.id'], ),
    sa.ForeignKeyConstraint(['send_intent_id'], ['send_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_reservations_company_id'), 'send_reservations', ['company_id'], unique=False)
    op.create_index(op.f('ix_send_reservations_company_policy_key'), 'send_reservations', ['company_policy_key'], unique=False)
    op.create_index(op.f('ix_send_reservations_normalized_recipient_email'), 'send_reservations', ['normalized_recipient_email'], unique=False)
    op.create_index(op.f('ix_send_reservations_policy_snapshot_id'), 'send_reservations', ['policy_snapshot_id'], unique=False)
    op.create_index(op.f('ix_send_reservations_reservation_id'), 'send_reservations', ['reservation_id'], unique=True)
    op.create_index(op.f('ix_send_reservations_send_intent_id'), 'send_reservations', ['send_intent_id'], unique=False)
    op.create_index(op.f('ix_send_reservations_status'), 'send_reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Destructive downgrade of Phase 2 domain tables is intentionally disabled.")
